### ISSUE TITLE
Move netlist rendering logic to netlistsvg

### ISSUE THREAD

**Issue by dvc94ch** [dvc94ch/pycircuit#22]
- [ ] port directions nturley/netlistsvg#34
- [ ] horizontal-vertical selection #33
- [ ] port swapping nturley/netlistsvg#17
